version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ultra
      MYSQL_USER: MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: 12345678
